### ISSUE TITLE
Make anonymous inner class a lambda

### ISSUE THREAD

**Issue by Peater68** [BME-MIT-IET/Sparql-Is-Fun-iet-2019#11]
Beans and Fields classes

**Comment by bargergo** [comment]
![kép](https://user-images.githubusercontent.com/37365034/57179164-f101c000-6e7a-11e9-8d1d-7566e6791df3.png)

![kép](https://user-images.githubusercontent.com/37365034/57179168-04ad2680-6e7b-11e9-9ff8-4a786ab148db.png)

![kép](https://user-images.githubusercontent.com/37365034/57179173-17bff680-6e7b-11e9-85da-637e32f01853.png)
