### ISSUE TITLE
Add JaCoCo to project

### ISSUE THREAD

**Issue by Peater68** [BME-MIT-IET/Sparql-Is-Fun-iet-2019#16]

**Comment by Peater68** [comment]
Használat:

1.  JaCoCo letöltése: https://www.eclemma.org/jacoco/  (8.4)
2.  ./gradlew build jacocoTestReport parancs kiadása
3. A keletkező build mappában lesz egy jacocoHtml mappa, amiben az index.html fájlt elindítva a böngészőben megjelennek a statisztikák.

**Comment by doliver97** [comment]
2. gradlew build jacocoTestReport működött nálam (./ nélkül)

**Comment by bargergo** [comment]
A JaCoCo-t nem kell külön letölteni, mert a gradle letölti
